### PR TITLE
chore: add react compiler eslint rules

### PR DESCRIPTION
**Pull request by L-Qun**
## Summary

If we want better support for the React Compiler, adding `eslint-plugin-react-compiler` might be a good choice, I think.

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks for the suggestion.
Can you open PRs to zustand and jotai too?
We try to keep the same eslint config among the three.

**Comment by L-Qun** [comment]
> Thanks for the suggestion. Can you open PRs to zustand and jotai too? We try to keep the same eslint config among the three.

@dai-shi Done

- valtio: https://github.com/pmndrs/valtio/pull/908
- zustand: https://github.com/pmndrs/zustand/pull/2612
- jotai: https://github.com/pmndrs/jotai/pull/2629

**Comment by L-Qun** [comment]
> > Thanks for the suggestion. Can you open PRs to zustand and jotai too? We try to keep the same eslint config among the three.
> 
> @dai-shi Done
> 
> * valtio: [chore: add react compiler eslint rules #908](https://github.com/pmndrs/valtio/pull/908)
> * zustand: [chore: add react compiler eslint rules zustand#2612](https://github.com/pmndrs/zustand/pull/2612)
> * jotai: [chore: add react compiler eslint rules jotai#2629](https://github.com/pmndrs/jotai/pull/2629)

@L-Qun 😊 Please let me know if there is anything else I need to do

**Review by dai-shi — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
