### PR TITLE
chore(examples): add todo with proxyMap example

### PR DESCRIPTION
**Pull request by fkhadra**
This PR add an example of todo app using `proxyMap`

[Edit valtio-proxy-map-todo](https://codesandbox.io/s/valtio-proxy-map-todo-3y0zt?fontsize=14&hidenavigation=1&theme=dark)

### CODE REVIEW

**Review by dai-shi — APPROVED** [review]
Tried this https://githubbox.com/pmndrs/valtio/tree/chore/add-proxyMap-example/examples/todo-with-proxyMap, but it shows an error. Let's merge this and see if it works in the main branch.

**Comment by dai-shi** [comment]
Hmm, https://githubbox.com/pmndrs/valtio/tree/main/examples/todo-with-proxyMap doesn't work.
But, https://githubbox.com/pmndrs/valtio/tree/main/examples/todo works.
Do you know what's the difference?

**Comment by fkhadra** [comment]
Tried the same. Could it be the camel case in the folder name?

**Comment by fkhadra** [comment]
Seems to work now

**Comment by dai-shi** [comment]
Thanks for confirming. Kind of cache? Good it's working now!

**Comment by fkhadra** [comment]
Not sure honestly. I went to codesanbox and I pasted  `https://github.com/pmndrs/valtio/tree/main/examples/todo-with-proxyMap` in the importer and then everything worked 😆. I guess next time we encounter the issue we can do the same.
Screenshot 2022-01-28 at 08 03 18

**Pull request merged**
