### PR TITLE
docs: restructure to api and guides with new async section

### LINKED ISSUE #534: Docs should include suspend async example
The [async example from the readme](https://github.com/pmndrs/valtio#suspend-your-components) should be included and highlighted in the docs. 
I read through all of the docs twice, and concluded I had to roll my own async utility.

### PR DESCRIPTION
**Pull request by RikuVan**
## Related Issues

Fixes #534

## Summary
New section to website documentation explaining how you can use promises with Valtio as well as Suspend while promises resolve.

## Check List

- [x] `yarn run prettier` for formatting code and docs

### CODE REVIEW

**Review by dai-shi — APPROVED** [review]
Thanks for working on this. The content looks good.
I wonder if it's your intention to add `async.mdx` there. At this moment, all `basic/`, `advanced/` and `hacks/` contain APIs. What we do in Jotai is to have `guides/`.
So, maybe:
- introduction
- guides
- APIs
  - basic, advanced, hacks

However, this would only be possible if we have more introduction and guides.

**Comment by RikuVan** [comment]
> Thanks for working on this. The content looks good. I wonder if it's your intention to add `async.mdx` there. At this moment, all `basic/`, `advanced/` and `hacks/` contain APIs. What we do in Jotai is to have `guides/`. So, maybe:
> 
> * introduction
> * guides
> * APIs
>   
>   * basic, advanced, hacks
> 
> However, this would only be possible if we have more introduction and guides.

Yep, that makes sense.

**Comment by RikuVan** [comment]
> > Thanks for working on this. The content looks good. I wonder if it's your intention to add `async.mdx` there. At this moment, all `basic/`, `advanced/` and `hacks/` contain APIs. What we do in Jotai is to have `guides/`. So, maybe:
> > 
> > * introduction
> > * guides
> > * APIs
> >   
> >   * basic, advanced, hacks
> > 
> > However, this would only be possible if we have more introduction and guides.
> 
> Yep, that makes sense. Don't merge this yet--I will have a look how easy that is tomorrow.

@dai-shi  is this what you had in mind?

Screenshot 2022-09-11 at 11 32 49

**Comment by dai-shi** [comment]
Yeah.

**Comment by RikuVan** [comment]
Updated with docs navigation changes.

**Comment by dai-shi** [comment]
Ready to merge?

**Pull request merged**
