### PR TITLE
feat: valtio/macro

### PR DESCRIPTION
**Pull request by dai-shi**
note: test requires build in advance. FIXME if possible.

### CODE REVIEW

**Comment by dai-shi** [comment]
> Error
Could not find path: '@babel/helper-module-imports'.

Hmm.

**Comment by dai-shi** [comment]
https://codesandbox.io/s/react-typescript-forked-4lmr2?file=/src/App.tsx
Minimal example.

**Comment by dai-shi** [comment]
Updated minimal example: https://codesandbox.io/s/react-typescript-forked-dfzh0?file=/src/App.tsx

**Comment by dai-shi** [comment]
If we push this feature, we could make breaking changes to rename hooks??
useProxy -> useSnapshot
useBoundProxy -> useProxy

ref: https://twitter.com/dai_shi/status/1366308344999288837

**Comment by drcmda** [comment]
sounds good, new major?

**Comment by dai-shi** [comment]
@drcmda Would you try it in some of your projects and see how it practically works?

> new major?

We can do minor and add deprecation notice, then major.

@Aslemammad would be surprised with renaming for his eslint-plugin-valtio.

**Comment by dai-shi** [comment]
> ofc i have no idea how any of this works, but it seems that would be optimal

I don't think it's easy to implement, or even possible.

proxy state is often defined in other files and imported, and also we can use a part of state.
```ts
import { state } from './somewhere' // is this proxy state or not?

  return <div>{state.foo.bar}</div> // should we subscribe to state or state.foo?
```

> another thing, if that macro is safe, doesn't cost much to ship - shouldn't it be the only default then? or are there downsides?

it only works with babel. requires some setup. 100% unsure if it's safe. 😓

**Comment by dai-shi** [comment]
> can't it also just be useSnapshot?

I think it's too confusing to have the same name for different purposes / functionalities.

Let's go with:
```js
import { useSnapshot } from 'valtio'
import { useProxy } from 'valtio/macro'
```

**Comment by dai-shi** [comment]
My misclick...

**Comment by dai-shi** [comment]
I will make a follow-up PR.

**Pull request merged**
