### PR TITLE
feat: addComputed

### LINKED ISSUE #85: Computed fields can't be added to nested objects
This would enable a computed to belong to the same namespace(i.e object) of a reactive property, for better organization

https://codesandbox.io/s/valtio-simple-counter-forked-z9mzx?file=/src/App.js

### LINKED ISSUE #86: A util method to add computed to state
Right now it's natural to add a reactive property to a proxified state object, what's missing is a util method for doing the same with computed:

```js
import { addComputed } from 'valtio/utils'
import state from './store/root' 

addComputed(state, { double(snap) { return snap.counter * 2 } })
```

### PR DESCRIPTION
**Pull request by dai-shi**
#90 trial made me think that valtio's computed model is different from other libraries concepts.
`proxyWithComputed` works with object getters because it is the same proxy object.
We can't support addComputed and nested with the same way.
So, here we add a new `addComputed`. Unfortunately, we can't infer typing nicely.

This should close #85 and close #86.

----

We put `addComputed` at first and then `proxyWithComputed` in readme. addComputed supports async well and we drop (undocumented / experimental) async from proxyWithComputed. However, async in addComputed is still experimental and not documented.

### CODE REVIEW

**Comment by dai-shi** [comment]
Should we name it `addComputed`?

**Comment by thelinuxlich** [comment]
addComputed would be better IMO

**Comment by thelinuxlich** [comment]
So this PR adds nested computeds and addComputed?

**Comment by dai-shi** [comment]
More precisely, I concluded that the ideal nested computed is not possible. You can get the similar result using addComputed (with the optional argument, we need to document this.)

**Comment by thelinuxlich** [comment]
I didn't saw a test demonstrating addComputed with get/set and nested, is the API different than proxyWithComputed then?

**Comment by dai-shi** [comment]
yes, different. Let me add some tests later.

And regretfully, I wasn't able to support `set` in addComputed. It could be with a different property like get for `.foo` and  set for `.setFoo()`, but then it doesn't have to be a util. At least, not for this one.

**Comment by thelinuxlich** [comment]
I see the optional third argument now. Why it can't be: 
```javascript
addComputed(
    state.math,
    {
      doubled: (snap) => computeDouble(snap.math.count),
    }
  )
```

**Comment by thelinuxlich** [comment]
btw if in the future we're able to support computed getter/setter with `addComputed` might as well remove `proxyWithComputed` to have only one way of having computeds in the state.

**Comment by dai-shi** [comment]
Oh, that was my desire as I wrote at first in #86.

> doubled: (snap) => computeDouble(snap.math.count),

No way to access this `snap`. It has to be `doubled: (snap) => computeDouble(snap.count),`, which is not "nested".

**Comment by thelinuxlich** [comment]
Why a state property is not nested, does valtio stores it in a flattened path internally?

**Comment by dai-shi** [comment]
Not sure what's you are asking. it's just js objects. you don't even know if there's only one parent.
```js
const obj1 = {}
const obj2 = {}
const child = {}
obj1.child = child
obj2.child = child
```
If you only get `child`, you don't know its parent.

**Comment by thelinuxlich** [comment]
That's what I thought, so I can't understand why you can't add the computed property to the reference as the first parameter

**Comment by dai-shi** [comment]
I guess you are confused with `proxyObject` and `targetObject`. The first argument is to create snapshot.

**Comment by thelinuxlich** [comment]
Still confused lol

**Comment by dai-shi** [comment]
Hm, not sure if I should merge this. Nobody is going to use it. I wish we could add this and drop `proxyWithComputed` but that's also a nice function with a cute hack.

Leaving it for a while..

**Comment by thelinuxlich** [comment]
Yeah, I feel like if you were able to drop the third parameter and have `addComputed(state, obj_with_computeds)` would be a cool replacement to `proxyWithComputed`

**Comment by dai-shi** [comment]
Didn't expect you say so. The third argument is for nesting and the big reason of developing `addComputed` over `proxyWithComputed`. addComputed doesn't support setter, which I'm personally fine, but it's one of the cute features in proxyWithComputed.

**Comment by thelinuxlich** [comment]
well, at least it's a optional argument :)

**Pull request merged**
