### PR TITLE
fix: remove bigint for rn

### LINKED ISSUE #41: it throws this error with react native, can't find bigint ?
Screen Shot 2020-12-08 at 2 32 15 PM

### PR DESCRIPTION
**Pull request by dai-shi**
close #41

### CODE REVIEW

**Comment by dai-shi** [comment]
@a-eid Now, does it still complain for anything else?

**Comment by a-eid** [comment]
@dai-shi I've not tested much using simply `proxy({ x: false })` triggers this.

**Comment by dai-shi** [comment]
@a-eid That's totally fine. It still helps. Please check the codesandbox bot message: https://github.com/pmndrs/valtio/pull/42#issuecomment-740595579
Click "click here" and you will see "Local Install Instructions".
Then, you can try the fix in the PR. Let me know if you have any issue with trying it.

**Comment by a-eid** [comment]
@dai-shi seems to work, thanks.

**Comment by dai-shi** [comment]
Great. Merging this.

**Pull request merged**
